###
GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Penttila Pham Vu Amelia Anh",
    "number": "09939231"
}